### ISSUE TITLE
Ensure that we are returning all tables touched in all statement types

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/wasm-sqlparser#54]
This is to ensure that downstream consumers of sql statements (like the sdk, and other clients) don't allow reads and joins between tables across test-/main-nets. This requires the work from: https://github.com/tablelandnetwork/go-sqlparser/pull/35

**Comment by carsonfarmer** [comment]
This is to ensure that downstream consumers of sql statements (like the sdk, and other clients) don't allow reads and joins between tables across test-/main-nets. This requires the work from: https://github.com/tablelandnetwork/go-sqlparser/pull/35

**Comment by jsign** [comment]
@carsonfarmer, I assigned this to you since I think is the correct thing (but feel free to change it). I also aligned the Milestone with the underlying project.

**Comment by carsonfarmer** [comment]
Fixed with #58
